In [2]:
import pandas as pd
import numpy as np

In [ ]:
df = pd.read_csv('Random_Data.csv')
students_marks = np.array([[67, 45],[90, 92],[66, 72],[32, 40]])
df = pd.DataFrame(students_marks, index=["Subodh", "Ram", "Abdul", "John"], columns=["Math", "Science"])
df += [10,20]

        Math  Science
Subodh    77       65
Ram      100      112
Abdul     76       92
John      42       60

In [ ]:
df1 = pd.DataFrame([
    {'name': 'bilal','salary': 30000},
    {'name': 'Shay','salary': 50000},
    {'name': 'Sam','salary': 40000},
    ])
df['total'] = df['Math'] + df['Science']

        Math  Science  total
Subodh    77       65    142
Ram      100      112    212
Abdul     76       92    168
John      42       60    102