In [9]:
import pandas as pd
import numpy as np
data = pd.read_csv('salary_data.csv')

In [36]:
data.head()

data['Salary'] = np.where(data['Years of Experience'] >= 15, 320000, data['Salary'])
# data['Salary'] = np.where(data['Years of Experience'] > 25, 400000, data['Salary'])

In [37]:
data.head()

,Age,Gender,Education Level,Job Title,Years of Experience,Salary
0,32.0,Male,Bachelor's,Software Engineer,5.0,90000.0
1,28.0,Female,Master's,Data Analyst,3.0,65000.0
2,45.0,Male,PhD,Senior Manager,15.0,320000.0
3,36.0,Female,Bachelor's,Sales Associate,7.0,60000.0
4,52.0,Male,Master's,Director,20.0,320000.0

In [52]:
data2 = pd.read_csv('salaries.csv')

data2.head()
data2[(data2['Salary'] > 20000) & (data2['Age'] < 60) & (data2['Job'] != 'Dentist')]

              Name  Age                Job  Salary
828  Vanessa Burns   59  Software Engineer   20300

In [53]:
data2.head()

              Name  Age                  Job  Salary
0    Kevin Sanders   24    Software Engineer    7300
1       Lisa Mills   26  High School Teacher    6100
2    Donna Allison   27              Dentist   12700
3  Michael Schmitt   43              Dentist   17500
4     Lisa Shaffer   31           Accountant    7400

In [ ]:

data2['Experience'] = np.random.randint(1, 23, data2.shape[0])

(1000, 5)

In [65]:
data2.head()

              Name  Age                  Job  Salary  Experience
0    Kevin Sanders   24    Software Engineer    7300           4
1       Lisa Mills   26  High School Teacher    6100           6
2    Donna Allison   27              Dentist   12700          15
3  Michael Schmitt   43              Dentist   17500           6
4     Lisa Shaffer   31           Accountant    7400          11

In [10]:
data['New_Salary'] = np.where((data['Age'] <= 30) & (data['Age'] >= 20), (data['Salary'] + (data['Salary'] * 0.1)), data['Salary'])

In [11]:
data['New_Salary'] = np.where((data['Age'] <= 40) & (data['Age'] > 30), (data['Salary'] * 1.2), data['New_Salary'])

In [12]:
data['New_Salary'] = np.where((data['Age'] <= 50) & (data['Age'] > 40), (data['Salary'] * 1.3), data['New_Salary'])

In [18]:
data.drop(columns=['Salary'],inplace=True)

In [19]:
data.rename(columns={'New_Salary': 'Salary'}, inplace=True)

In [20]:
data.head()

,Age,Gender,Education Level,Job Title,Years of Experience,Salary
0,32.0,Male,Bachelor's,Software Engineer,5.0,108000.0
1,28.0,Female,Master's,Data Analyst,3.0,71500.0
2,45.0,Male,PhD,Senior Manager,15.0,195000.0
3,36.0,Female,Bachelor's,Sales Associate,7.0,72000.0
4,52.0,Male,Master's,Director,20.0,200000.0