In [1]:
import pandas as pd
import numpy as np

In [ ]:
data = pd.read_csv('data.csv')
# select few columns
# data = data[['column1', 'column2', 'column3']]
data = data[['Accident Number', 'Number of Motor Vehicles', 'Number of Injuries' ,'Number of Fatalities', 'Hit and Run', 'City', 'State']]
data.head()

,Accident Number,Number of Motor Vehicles,Number of Injuries,Number of Fatalities,Hit and Run,City,State
0,2008473471,2.0,2.0,0.0,N,NASHVILLE,TN
1,2008787228,1.0,1.0,0.0,N,NASHVILLE,TN
2,2009131786,1.0,1.0,0.0,N,NASHVILLE,TN
3,2009418107,2.0,0.0,0.0,Y,NaN,TN
4,20120135824,2.0,1.0,0.0,N,NASHVILLE,TN

In [22]:
a = np.arange(1,10).reshape(3,3)
a = pd.DataFrame(a,columns=['A','B','C'], index=[1,2,3])
a.head(),
a.tail(),
a.info(),
a.describe(),

<class 'pandas.core.frame.DataFrame'>
Index: 3 entries, 1 to 3
Data columns (total 3 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   A       3 non-null      int64
 1   B       3 non-null      int64
 2   C       3 non-null      int64
dtypes: int64(3)
memory usage: 96.0 bytes

(         A    B    C
 count  3.0  3.0  3.0
 mean   4.0  5.0  6.0
 std    3.0  3.0  3.0
 min    1.0  2.0  3.0
 25%    2.5  3.5  4.5
 50%    4.0  5.0  6.0
 75%    5.5  6.5  7.5
 max    7.0  8.0  9.0,)

In [49]:
b = pd.read_csv('data.csv')

b['Property Damage'].fillna('None', inplace=True)
b['Illumination Description'].fillna('None', inplace=True)
b['HarmfulDescriptions'].fillna('None', inplace=True)
b.head()
c = b.copy()

/tmp/ipykernel_1625/1911127842.py:3: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  b['Property Damage'].fillna('None', inplace=True)
/tmp/ipykernel_1625/1911127842.py:4: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  b['Illumination Description'].fillna('None', inplace=True)
/tmp/ipykernel_1625/1911127842.py:5: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  b['HarmfulDescriptions'].fillna('None', inplace=True)

In [ ]:
# Filtering
b.loc[(b['Collision Type Description'] == 'HEAD-ON') & (b['Hit and Run'] == 'Y') & (b['Number of Fatalities'] >= 1.0)]

,Accident Number,Date and Time,Number of Motor Vehicles,Number of Injuries,Number of Fatalities,Property Damage,Hit and Run,Collision Type Description,Weather Description,Illumination Description,...,HarmfulDescriptions,ObjectId,Zip Code,RPA,Weather,IlluACCIDEmination,Collision Type,Reporting Officer,x,y
34455,20181007333,12/4/2018 9:25:00 AM,2.0,0.0,1.0,None,Y,HEAD-ON,CLEAR,DARK - NOT LIGHTED,...,MOTOR VEHICLE IN TRANSPORT;DITCH,34456,37135.0,8773.0,21.0,2.0,2.0,493312.0,-9.646372e+06,4.299508e+06
127506,20210610551,11/30/2021 7:13:00 AM,0.0,2.0,1.0,None,Y,HEAD-ON,CLEAR,DARK - LIGHTED,...,MOTOR VEHICLE IN TRANSPORT;Ran Off Road-Right,127507,37013.0,8869.0,21.0,3.0,2.0,887598.0,-9.642072e+06,4.303822e+06

In [40]:
c['Number of Fatalities'] = c['Number of Fatalities'] * 10

In [42]:
c.loc[c['Number of Fatalities'] > 0]

,Accident Number,Date and Time,Number of Motor Vehicles,Number of Injuries,Number of Fatalities,Property Damage,Hit and Run,Collision Type Description,Weather Description,Illumination Description,...,HarmfulDescriptions,ObjectId,Zip Code,RPA,Weather,IlluACCIDEmination,Collision Type,Reporting Officer,x,y
19,20170728702,8/25/2018 10:12:00 AM,2.0,0.0,20.0,None,N,HEAD-ON,CLEAR,DARK - NOT LIGHTED,...,MOTOR VEHICLE IN TRANSPORT,20,37013.0,8869.0,21.0,2.0,2.0,345098.0,-9.639540e+06,4.304888e+06
283,20180009171,1/4/2018 1:18:00 AM,1.0,0.0,20.0,None,N,NOT COLLISION W/MOTOR VEHICLE-TRANSPORT,CLEAR,DARK - LIGHTED,...,PEDESTRIAN,284,37207.0,1861.0,21.0,3.0,0.0,345098.0,-9.659009e+06,4.329084e+06
1031,20180058575,1/19/2018 12:12:00 AM,1.0,0.0,20.0,None,N,NOT COLLISION W/MOTOR VEHICLE-TRANSPORT,CLEAR,DARK - LIGHTED,...,PEDESTRIAN,1032,37217.0,8815.0,21.0,3.0,0.0,240943.0,-9.653536e+06,4.318859e+06
1706,20180041747,1/14/2018 12:42:00 AM,1.0,0.0,20.0,None,N,NOT COLLISION W/MOTOR VEHICLE-TRANSPORT,CLEAR,DARK - NOT LIGHTED,...,PEDESTRIAN,1707,37013.0,88060.0,21.0,2.0,0.0,226095.0,-9.645635e+06,4.306004e+06
2488,20180066566,1/21/2018 10:12:00 AM,1.0,4.0,20.0,Y,N,NOT COLLISION W/MOTOR VEHICLE-TRANSPORT,CLEAR,DARK - LIGHTED,...,OTHER OBJECT (NOT FIXED);BUILDING,2489,37217.0,8939.0,21.0,3.0,0.0,468097.0,-9.644659e+06,4.310992e+06
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
214595,20250192635,3/27/2025 6:13:00 AM,5.0,2.0,40.0,None,N,Front to Rear,CLEAR,DARK - LIGHTED,...,MOTOR VEHICLE IN TRANSPORT,214596,37013.0,8702.0,21.0,3.0,11.0,462474.0,-9.642235e+06,4.302234e+06
214605,20250193052,3/27/2025 12:53:00 PM,3.0,3.0,40.0,None,N,HEAD-ON,CLEAR,DAYLIGHT,...,MOTOR VEHICLE IN TRANSPORT;DITCH,214606,37080.0,2315.0,21.0,1.0,2.0,887592.0,-9.673079e+06,4.353260e+06
214700,20250195399,3/28/2025 8:37:00 AM,1.0,0.0,20.0,None,N,NOT COLLISION W/MOTOR VEHICLE-TRANSPORT,CLEAR,DARK - LIGHTED,...,Motor Vehicle-In-Motion Outside Trafficw;EMBAN...,214701,37207.0,1887.0,21.0,3.0,0.0,462474.0,-9.656830e+06,4.330771e+06
214764,20250196835,3/28/2025 11:35:00 PM,1.0,1.0,20.0,None,N,NOT COLLISION W/MOTOR VEHICLE-TRANSPORT,CLOUDY,DAYLIGHT,...,WALL;Ran Off Road-Left,214765,37210.0,9004.0,22.0,1.0,0.0,330413.0,-9.654601e+06,4.319891e+06
215245,20250203151,4/1/2025 1:34:00 AM,1.0,0.0,40.0,Y,N,NOT COLLISION W/MOTOR VEHICLE-TRANSPORT,CLEAR,DARK - LIGHTED,...,UTILITY POLE;Ran Off Road-Right,215246,37138.0,9711.0,21.0,3.0,0.0,352156.0,-9.643878e+06,4.333795e+06

In [45]:
c['Hit and Run'] = c['Hit and Run'].replace(to_replace='N', value='No')
c['Hit and Run'] = c['Hit and Run'].replace(to_replace='Y', value='Yes')
c.head()

,Accident Number,Date and Time,Number of Motor Vehicles,Number of Injuries,Number of Fatalities,Property Damage,Hit and Run,Collision Type Description,Weather Description,Illumination Description,...,HarmfulDescriptions,ObjectId,Zip Code,RPA,Weather,IlluACCIDEmination,Collision Type,Reporting Officer,x,y
0,2008473471,7/14/2018 11:00:00 PM,2.0,2.0,0.0,None,No,ANGLE,NO ADVERSE CONDITIONS,None,...,None,1,37208.0,4525.0,1.0,1.0,4.0,225845.0,-9.664843e+06,4.323742e+06
1,2008787228,11/16/2018 9:33:00 AM,1.0,1.0,0.0,None,No,NOT COLLISION W/MOTOR VEHICLE-TRANSPORT,NO ADVERSE CONDITIONS,None,...,None,2,37203.0,5401.0,1.0,3.0,0.0,475881.0,-9.662645e+06,4.322558e+06
2,2009131786,2/19/2019 10:42:00 PM,1.0,1.0,0.0,None,No,HEAD-ON,NO ADVERSE CONDITIONS,None,...,None,3,37218.0,3235.0,1.0,1.0,2.0,562528.0,-9.674832e+06,4.329570e+06
3,2009418107,5/27/2019 9:00:00 PM,2.0,0.0,0.0,None,Yes,REAR END,NO ADVERSE CONDITIONS,None,...,None,4,NaN,4311.0,1.0,1.0,1.0,571315.0,-9.659749e+06,4.323487e+06
4,20120135824,3/8/2021 6:05:00 PM,2.0,1.0,0.0,None,No,Front to Rear,CLEAR,DAYLIGHT,...,MOTOR VEHICLE IN TRANSPORT,5,37207.0,1863.0,21.0,1.0,11.0,473670.0,-9.659079e+06,4.328993e+06

In [ ]:
c = c.iloc[:, [1, 2, 3, 4, 5, 6, 7, 10, 11]]
c.head()

,Date and Time,Number of Motor Vehicles,Number of Injuries,Number of Fatalities,Property Damage,Hit and Run,Collision Type Description,Street Address,City
0,7/14/2018 11:00:00 PM,2.0,2.0,0.0,None,N,ANGLE,28TH AVE N & JEFFERSON ST,NASHVILLE
1,11/16/2018 9:33:00 AM,1.0,1.0,0.0,None,N,NOT COLLISION W/MOTOR VEHICLE-TRANSPORT,DR D B TODD JR BLVD & PEARL ST,NASHVILLE
2,2/19/2019 10:42:00 PM,1.0,1.0,0.0,None,N,HEAD-ON,4953 ASHLAND CITY HWY,NASHVILLE
3,5/27/2019 9:00:00 PM,2.0,0.0,0.0,None,Y,REAR END,JEFFERSON ST & 1ST AV N,NaN
4,3/8/2021 6:05:00 PM,2.0,1.0,0.0,None,N,Front to Rear,W TRINITY LN & E TRINITY LN,NASHVILLE

In [52]:
c.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 216117 entries, 0 to 216116
Data columns (total 9 columns):
 #   Column                      Non-Null Count   Dtype
---  ------                      --------------   -----
 0   Date and Time               216117 non-null  object
 1   Number of Motor Vehicles    216113 non-null  float64
 2   Number of Injuries          216114 non-null  float64
 3   Number of Fatalities        216114 non-null  float64
 4   Property Damage             216117 non-null  object
 5   Hit and Run                 216103 non-null  object
 6   Collision Type Description  203143 non-null  object
 7   Street Address              215881 non-null  object
 8   City                        216113 non-null  object
dtypes: float64(3), object(6)
memory usage: 14.8+ MB

In [53]:
c.head()

,Date and Time,Number of Motor Vehicles,Number of Injuries,Number of Fatalities,Property Damage,Hit and Run,Collision Type Description,Street Address,City
0,7/14/2018 11:00:00 PM,2.0,2.0,0.0,None,N,ANGLE,28TH AVE N & JEFFERSON ST,NASHVILLE
1,11/16/2018 9:33:00 AM,1.0,1.0,0.0,None,N,NOT COLLISION W/MOTOR VEHICLE-TRANSPORT,DR D B TODD JR BLVD & PEARL ST,NASHVILLE
2,2/19/2019 10:42:00 PM,1.0,1.0,0.0,None,N,HEAD-ON,4953 ASHLAND CITY HWY,NASHVILLE
3,5/27/2019 9:00:00 PM,2.0,0.0,0.0,None,Y,REAR END,JEFFERSON ST & 1ST AV N,NaN
4,3/8/2021 6:05:00 PM,2.0,1.0,0.0,None,N,Front to Rear,W TRINITY LN & E TRINITY LN,NASHVILLE

In [54]:
c.loc[2,'Collision Type Description'] = 'ANGLE'
c.head()

,Date and Time,Number of Motor Vehicles,Number of Injuries,Number of Fatalities,Property Damage,Hit and Run,Collision Type Description,Street Address,City
0,7/14/2018 11:00:00 PM,2.0,2.0,0.0,None,N,ANGLE,28TH AVE N & JEFFERSON ST,NASHVILLE
1,11/16/2018 9:33:00 AM,1.0,1.0,0.0,None,N,NOT COLLISION W/MOTOR VEHICLE-TRANSPORT,DR D B TODD JR BLVD & PEARL ST,NASHVILLE
2,2/19/2019 10:42:00 PM,1.0,1.0,0.0,None,N,ANGLE,4953 ASHLAND CITY HWY,NASHVILLE
3,5/27/2019 9:00:00 PM,2.0,0.0,0.0,None,Y,REAR END,JEFFERSON ST & 1ST AV N,NaN
4,3/8/2021 6:05:00 PM,2.0,1.0,0.0,None,N,Front to Rear,W TRINITY LN & E TRINITY LN,NASHVILLE

In [56]:
c.sort_values(['Number of Fatalities', 'Number of Injuries'], ascending=[0,1])

,Date and Time,Number of Motor Vehicles,Number of Injuries,Number of Fatalities,Property Damage,Hit and Run,Collision Type Description,Street Address,City
187319,2/11/2024 12:45:00 PM,2.0,1.0,4.0,None,N,HEAD-ON,BELL RD & BRENTRIDGE DR,ANTIOCH
168739,6/18/2023 5:07:00 AM,1.0,0.0,3.0,Y,N,NOT COLLISION W/MOTOR VEHICLE-TRANSPORT,POWELL AV & SIDCO DR,NASHVILLE
177786,10/8/2023 8:04:00 AM,1.0,0.0,3.0,None,N,NOT COLLISION W/MOTOR VEHICLE-TRANSPORT,NaN,ANTIOCH
107551,3/11/2021 10:11:00 PM,2.0,1.0,3.0,None,N,Front to Rear,MM 200 3 I 40,NASHVILLE
186545,2/18/2024 2:39:00 AM,2.0,5.0,3.0,Y,N,ANGLE,S 1ST ST & WOODLAND ST,NASHVILLE
...,...,...,...,...,...,...,...,...,...
157910,12/31/2022 1:45:00 PM,3.0,12.0,0.0,None,N,HEAD-ON,BROADMOOR DR & DICKERSON PKE,NASHVILLE
210371,1/24/2025 6:00:00 AM,9.0,12.0,0.0,None,Y,ANGLE,MM 212 0 I-24,NASHVILLE
7,12/22/2020 6:00:00 AM,NaN,NaN,NaN,None,NaN,NaN,NaN,NaN
16133,6/19/2018 4:00:00 PM,NaN,NaN,NaN,None,NaN,NaN,COLLIER AVE & NOLENSVILLE PIKE,NASHVILLE
22700,8/30/2018 5:58:00 PM,NaN,NaN,NaN,None,NaN,NaN,NaN,NaN