In [5]:
# %pip install --upgrade transformers
%pip install -U accelerate transformers[torch]
# %pip install -U transformers
# %pip uninstall -y transformers

# %pip install datasets transformers[sentencepiece]
# %pip install sentencepiece
# %pip install torch torchvision torchaudio --index-url https://download.pytorch.org/whl/cu118

Requirement already satisfied: accelerate in /home/bilal/Learning_Paths/.venv/lib/python3.12/site-packages (1.10.1)
Collecting transformers[torch]
  Using cached transformers-4.57.1-py3-none-any.whl.metadata (43 kB)
Requirement already satisfied: numpy<3.0.0,>=1.17 in /home/bilal/Learning_Paths/.venv/lib/python3.12/site-packages (from accelerate) (2.3.3)
Requirement already satisfied: packaging>=20.0 in /home/bilal/Learning_Paths/.venv/lib/python3.12/site-packages (from accelerate) (25.0)
Requirement already satisfied: psutil in /home/bilal/Learning_Paths/.venv/lib/python3.12/site-packages (from accelerate) (7.0.0)
Requirement already satisfied: pyyaml in /home/bilal/Learning_Paths/.venv/lib/python3.12/site-packages (from accelerate) (6.0.3)
Requirement already satisfied: torch>=2.0.0 in /home/bilal/Learning_Paths/.venv/lib/python3.12/site-packages (from accelerate) (2.7.1+cu118)
Requirement already satisfied: huggingface_hub>=0.21.0 in /home/bilal/Learning_Paths/.venv/lib/python3.12/site-packages (from accelerate) (0.35.3)
Requirement already satisfied: safetensors>=0.4.3 in /home/bilal/Learning_Paths/.venv/lib/python3.12/site-packages (from accelerate) (0.6.2)
Requirement already satisfied: filelock in /home/bilal/Learning_Paths/.venv/lib/python3.12/site-packages (from transformers[torch]) (3.20.0)
Requirement already satisfied: regex!=2019.12.17 in /home/bilal/Learning_Paths/.venv/lib/python3.12/site-packages (from transformers[torch]) (2025.9.18)
Requirement already satisfied: requests in /home/bilal/Learning_Paths/.venv/lib/python3.12/site-packages (from transformers[torch]) (2.32.5)
Requirement already satisfied: tokenizers<=0.23.0,>=0.22.0 in /home/bilal/Learning_Paths/.venv/lib/python3.12/site-packages (from transformers[torch]) (0.22.1)
Requirement already satisfied: tqdm>=4.27 in /home/bilal/Learning_Paths/.venv/lib/python3.12/site-packages (from transformers[torch]) (4.67.1)
Requirement already satisfied: fsspec>=2023.5.0 in /home/bilal/Learning_Paths/.venv/lib/python3.12/site-packages (from huggingface_hub>=0.21.0->accelerate) (2025.9.0)
Requirement already satisfied: typing-extensions>=3.7.4.3 in /home/bilal/Learning_Paths/.venv/lib/python3.12/site-packages (from huggingface_hub>=0.21.0->accelerate) (4.15.0)
Requirement already satisfied: hf-xet<2.0.0,>=1.1.3 in /home/bilal/Learning_Paths/.venv/lib/python3.12/site-packages (from huggingface_hub>=0.21.0->accelerate) (1.1.10)
Requirement already satisfied: setuptools in /home/bilal/Learning_Paths/.venv/lib/python3.12/site-packages (from torch>=2.0.0->accelerate) (70.2.0)
Requirement already satisfied: sympy>=1.13.3 in /home/bilal/Learning_Paths/.venv/lib/python3.12/site-packages (from torch>=2.0.0->accelerate) (1.14.0)
Requirement already satisfied: networkx in /home/bilal/Learning_Paths/.venv/lib/python3.12/site-packages (from torch>=2.0.0->accelerate) (3.5)
Requirement already satisfied: jinja2 in /home/bilal/Learning_Paths/.venv/lib/python3.12/site-packages (from torch>=2.0.0->accelerate) (3.1.6)
Requirement already satisfied: nvidia-cuda-nvrtc-cu11==11.8.89 in /home/bilal/Learning_Paths/.venv/lib/python3.12/site-packages (from torch>=2.0.0->accelerate) (11.8.89)
Requirement already satisfied: nvidia-cuda-runtime-cu11==11.8.89 in /home/bilal/Learning_Paths/.venv/lib/python3.12/site-packages (from torch>=2.0.0->accelerate) (11.8.89)
Requirement already satisfied: nvidia-cuda-cupti-cu11==11.8.87 in /home/bilal/Learning_Paths/.venv/lib/python3.12/site-packages (from torch>=2.0.0->accelerate) (11.8.87)
Requirement already satisfied: nvidia-cudnn-cu11==9.1.0.70 in /home/bilal/Learning_Paths/.venv/lib/python3.12/site-packages (from torch>=2.0.0->accelerate) (9.1.0.70)
Requirement already satisfied: nvidia-cublas-cu11==11.11.3.6 in /home/bilal/Learning_Paths/.venv/lib/python3.12/site-packages (from torch>=2.0.0->accelerate) (11.11.3.6)
Requirement already satisfied: nvidia-cufft-cu11==10.9.0.58 in /home/bilal/Learning_Paths/.venv/lib/python3.12/site-packages (from torch>=2.0.0->accelerate) (10.9.0.58)
Requirement already satisfied: nvidia-curand-cu11==10.3.0.86 in /home/bilal/Learning_Paths/.venv/lib/python3.12/site-packages (from torch>=2.0.0->accelerate) (10.3.0.86)
Requirement already satisfied: nvidia-cusolver-cu11==11.4.1.48 in /home/bilal/Learning_Paths/.venv/lib/python3.12/site-packages (from torch>=2.0.0->accelerate) (11.4.1.48)
Requirement already satisfied: nvidia-cusparse-cu11==11.7.5.86 in /home/bilal/Learning_Paths/.venv/lib/python3.12/site-packages (from torch>=2.0.0->accelerate) (11.7.5.86)
Requirement already satisfied: nvidia-nccl-cu11==2.21.5 in /home/bilal/Learning_Paths/.venv/lib/python3.12/site-packages (from torch>=2.0.0->accelerate) (2.21.5)
Requirement already satisfied: nvidia-nvtx-cu11==11.8.86 in /home/bilal/Learning_Paths/.venv/lib/python3.12/site-packages (from torch>=2.0.0->accelerate) (11.8.86)
Requirement already satisfied: triton==3.3.1 in /home/bilal/Learning_Paths/.venv/lib/python3.12/site-packages (from torch>=2.0.0->accelerate) (3.3.1)
Requirement already satisfied: mpmath<1.4,>=1.1.0 in /home/bilal/Learning_Paths/.venv/lib/python3.12/site-packages (from sympy>=1.13.3->torch>=2.0.0->accelerate) (1.3.0)
Requirement already satisfied: MarkupSafe>=2.0 in /home/bilal/Learning_Paths/.venv/lib/python3.12/site-packages (from jinja2->torch>=2.0.0->accelerate) (2.1.5)
Requirement already satisfied: charset_normalizer<4,>=2 in /home/bilal/Learning_Paths/.venv/lib/python3.12/site-packages (from requests->transformers[torch]) (3.4.3)
Requirement already satisfied: idna<4,>=2.5 in /home/bilal/Learning_Paths/.venv/lib/python3.12/site-packages (from requests->transformers[torch]) (3.11)
Requirement already satisfied: urllib3<3,>=1.21.1 in /home/bilal/Learning_Paths/.venv/lib/python3.12/site-packages (from requests->transformers[torch]) (2.5.0)
Requirement already satisfied: certifi>=2017.4.17 in /home/bilal/Learning_Paths/.venv/lib/python3.12/site-packages (from requests->transformers[torch]) (2025.10.5)
Using cached transformers-4.57.1-py3-none-any.whl (12.0 MB)
Installing collected packages: transformers
Successfully installed transformers-4.57.1
Note: you may need to restart the kernel to use updated packages.

In [1]:
import pandas as pd, json

In [3]:
pii_dataset = pd.read_csv('processed_pii_dataset.csv', usecols=['text', 'json'], nrows=1000)
pii_dataset.head()

,text,json
0,"My name is Aaliyah Popova, and I am a jeweler ...","{""name"": ""Aaliyah Popova"", ""email"": ""aaliyah.p..."
1,"My name is Konstantin Becker, and I'm a develo...","{""name"": ""Konstantin Becker"", ""email"": ""konsta..."
2,"As Mieko Mitsubishi, an account manager at a p...","{""name"": ""Mieko Mitsubishi"", ""email"": ""mieko_m..."
3,"My name is Kazuo Sun, and I'm an air traffic c...","{""name"": ""Kazuo Sun"", ""email"": ""kazuosun@hotma..."
4,"My name is Arina Sun, and I'm a dental hygieni...","{""name"": ""Arina Sun"", ""email"": ""arina-sun@gmai..."

In [4]:
pii_dataset['target_json'] = pii_dataset['json']
pii_dataset = pii_dataset.rename(columns={"text": "input_text"})  # Rename for clarity
pii_dataset

,input_text,json,target_json
0,"My name is Aaliyah Popova, and I am a jeweler ...","{""name"": ""Aaliyah Popova"", ""email"": ""aaliyah.p...","{""name"": ""Aaliyah Popova"", ""email"": ""aaliyah.p..."
1,"My name is Konstantin Becker, and I'm a develo...","{""name"": ""Konstantin Becker"", ""email"": ""konsta...","{""name"": ""Konstantin Becker"", ""email"": ""konsta..."
2,"As Mieko Mitsubishi, an account manager at a p...","{""name"": ""Mieko Mitsubishi"", ""email"": ""mieko_m...","{""name"": ""Mieko Mitsubishi"", ""email"": ""mieko_m..."
3,"My name is Kazuo Sun, and I'm an air traffic c...","{""name"": ""Kazuo Sun"", ""email"": ""kazuosun@hotma...","{""name"": ""Kazuo Sun"", ""email"": ""kazuosun@hotma..."
4,"My name is Arina Sun, and I'm a dental hygieni...","{""name"": ""Arina Sun"", ""email"": ""arina-sun@gmai...","{""name"": ""Arina Sun"", ""email"": ""arina-sun@gmai..."
...,...,...,...
995,"Lucy Lange, a dedicated and passionate nutriti...","{""name"": ""Lucy Lange"", ""email"": ""lucy_lange@ao...","{""name"": ""Lucy Lange"", ""email"": ""lucy_lange@ao..."
996,"Krishna Weber, an architect with a keen eye fo...","{""name"": ""Krishna Weber"", ""email"": ""krishna-we...","{""name"": ""Krishna Weber"", ""email"": ""krishna-we..."
997,"As Kash Weiss, a seasoned butcher with years o...","{""name"": ""Kash Weiss"", ""email"": ""kash_weiss521...","{""name"": ""Kash Weiss"", ""email"": ""kash_weiss521..."
998,In the realm of intellectual curiosity and aca...,"{""name"": ""Justin Schmitt"", ""email"": ""justinsch...","{""name"": ""Justin Schmitt"", ""email"": ""justinsch..."
999,"Hello, my name is Sean Butcher. I'm writing th...","{""name"": ""Sean Butcher"", ""email"": ""seanbutcher...","{""name"": ""Sean Butcher"", ""email"": ""seanbutcher..."

In [5]:
from datasets import Dataset
pii_dataset = Dataset.from_pandas(pii_dataset[['input_text', 'target_json']])
pii_dataset = pii_dataset.train_test_split(test_size=0.2)

/home/bilal/Learning_Paths/.venv/lib/python3.12/site-packages/tqdm/auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm

In [39]:
pii_dataset['train']["input_text"]

Column(["My name is Konstantin Becker, and I'm a developer with two years of experience. I recently worked on a project where we built a new customer portal for our company. The goal was to create a more user-friendly and intuitive interface that would make it easier for customers to manage their accounts and access information. We started by gathering requirements from our customers and conducting user research to understand their needs and pain points. We then designed a new user interface that was both visually appealing and easy to use. We also implemented a number of new features, such as the ability for customers to view their account history, track their orders, and submit support tickets online. The project was a success, and our customers were very happy with the new portal. They found it to be much easier to use than the old one, and they appreciated the new features. We saw a significant increase in customer satisfaction and engagement as a result of the new portal. Throughout the project, I was responsible for developing the back-end code for the portal. I also worked closely with the design team to ensure that the portal was visually appealing and user-friendly. I'm proud of the work that I did on this project, and I'm confident that it will continue to benefit our customers for years to come. If you would like to contact me, my email address is konstantin.becker@gmail.com and my phone number is 0475 4429797. I live at 826 Webster Street. Quilting is my hobby.", "My name is Kuo Lopez and I've been a professor for 8 years. I have a strong passion for education and strive to create engaging and interactive learning experiences for my students. One project that I'm particularly proud of is the development of an online learning platform for my Environmental Science course. I wanted to create a platform that would allow students to learn at their own pace and provide them with a variety of resources to enhance their understanding of the material. I spent several months working on the platform, which included designing the layout, creating interactive modules, and developing assessments. I also incorporated multimedia elements such as videos, simulations, and animations to make the learning experience more engaging. The platform was a huge success with my students. They appreciated the flexibility and convenience of being able to learn at their own pace, and they found the interactive modules and multimedia elements to be very helpful. The platform also allowed me to track student progress and provide feedback more efficiently. One of the challenges I faced during this project was ensuring that the platform was accessible to all students, regardless of their technical skills or devices. I made sure to use a user-friendly design and provide clear instructions on how to use the platform. I also tested the platform extensively to ensure that it worked properly on different devices and browsers. Overall, the development of the online learning platform was a rewarding experience. It allowed me to use my creativity and technical skills to create a resource that had a positive impact on my students' learning. I am always looking for new ways to improve my teaching and I'm excited to continue developing innovative learning experiences for my students. Contact Information: Kuo Lopez 4188 Summerview Drive +27 49 207 3764 kuolopez@hotmail.com Hobbies: Kite surfing", "My name is Kazuo Sun, and I'm an air traffic controller with seven years of experience. I've always been fascinated by aviation, and I love the challenge of keeping planes safe and on time. One of the most memorable projects I worked on was a major upgrade to our airport's radar system. The old system was outdated and prone to breakdowns, and it was becoming increasingly difficult to keep up with the growing number of flights. I was assigned to the team that was responsible for planning and implementing the upgrade. We worked closely with the engineers and technicians to design a new system that would be more reliable, efficient, and capable. The project took several months to complete, and it was a lot of hard work. But in the end, it was worth it. The new radar system has been a major improvement, and it has helped us to improve the safety and efficiency of our airport. I'm proud of the work that I did on this project, and I'm grateful for the opportunity to have been a part of it. It was a challenging experience, but it also taught me a lot about teamwork, problem-solving, and the importance of staying up-to-date on the latest technology. Outside of work, I enjoy spending time with my family and friends. I also enjoy amateur radio and tinkering with electronics. I'm always looking for new projects to work on, and I'm always learning new things. If you'd like to get in touch with me, you can reach me by phone at 0304 2215930 or by email at kazuosun@hotmail.net. You can also find me at my home address, which is 736 Sicard Street Southeast.", "My name is Alexander Tanaka, and I'm a saleswoman with a year of experience. I recently completed a project that involved developing and implementing a new sales strategy for my company. I started by analyzing our current sales data to identify areas where we could improve. I found that we were losing a lot of potential customers because our sales process was too complicated and time-consuming. So, I streamlined the process and made it easier for customers to make purchases. I also created a new marketing campaign to generate more leads for our sales team. I used a variety of marketing channels, including social media, email, and paid advertising. The campaign was a success, and we saw a significant increase in the number of leads we were generating. As a result of these changes, our sales increased by 20% in the first quarter. I'm proud of the work that I did on this project, and I'm confident that it will continue to help my company grow in the future. Outside of work, I enjoy metalworking. I find it to be a relaxing and rewarding hobby. I also enjoy spending time with my family and friends. If you have any questions about my sales strategy project or my hobbies, you can reach me at +86 10746 1491 or alexandertanaka@hotmail.net. You can also visit me at my home address, which is 1890 Orchard View Road.", "As Mieko Mitsubishi, an account manager at a prominent software company, I encountered a unique challenge that required my utmost dedication and expertise to solve. The issue arose when one of our valued clients, a leading multinational corporation, reported inconsistencies in their data analytics platform. The discrepancies were affecting their decision-making processes and causing uncertainty within their operations. With a sense of urgency, I delved into the intricacies of the problem, carefully examining the data sets, algorithms, and underlying infrastructure. I spent countless hours poring over lines of code, analyzing patterns, and conducting thorough testing to pinpoint the root cause of the discrepancies. My unwavering commitment to excellence and meticulous attention to detail eventually led me to identify a subtle bug in the system's architecture. To rectify the situation, I collaborated closely with our team of engineers, providing clear and concise instructions to address the bug and implement a comprehensive solution. Our collective efforts resulted in the successful resolution of the issue, restoring accuracy and reliability to the client's data analytics platform. The client expressed their immense gratitude for our prompt and effective response, reaffirming their trust in our services. It is moments like these that remind me of the immense satisfaction that comes from solving complex problems and making a positive impact on our clients' businesses. I take immense pride in my ability to identify and resolve challenges with ingenuity and precision. My unwavering commitment to excellence and passion for delivering exceptional results drive me to consistently exceed expectations. Mieko Mitsubishi Account Manager 1309 Southwest 71st Terrace mieko_mitsubishi@msn.org"])

In [6]:
from transformers import T5Tokenizer

# tokenizer = T5Tokenizer.from_pretrained("t5-large")
tokenizer = T5Tokenizer.from_pretrained('./model/t5_tokenizer')

max_input_length = 512
max_target_length = 256

def preprocess(example):
    input_text = example["input_text"]
    target_text = example["target_json"]
    
    model_input = tokenizer(
        input_text,
        max_length=max_input_length,
        padding="max_length",
        truncation=True,
        return_tensors="pt",
    )
    
    with tokenizer.as_target_tokenizer():
        labels = tokenizer(
            target_text,
            max_length=max_target_length,
            padding="max_length",
            truncation=True,
            return_tensors="pt",
        )

    model_input["labels"] = labels["input_ids"][0]
    model_input["attention_mask"] = model_input["attention_mask"][0]
    model_input["input_ids"] = model_input["input_ids"][0]
    # print(model_input)
    return model_input
tokenized_dataset = {}
tokenized_dataset = pii_dataset.map(preprocess)

Map:   0%|          | 0/800 [00:00<?, ? examples/s]/home/bilal/Learning_Paths/.venv/lib/python3.12/site-packages/transformers/tokenization_utils_base.py:4034: UserWarning: `as_target_tokenizer` is deprecated and will be removed in v5 of Transformers. You can tokenize your labels by using the argument `text_target` of the regular `__call__` method (either in the same call as your input texts if you use the same keyword arguments, or in a separate call.
  warnings.warn(
Map: 100%|██████████| 800/800 [00:02<00:00, 298.25 examples/s]
Map: 100%|██████████| 200/200 [00:00<00:00, 311.32 examples/s]

In [61]:
print("Input ID", tokenized_dataset['train']['input_ids'])
print("Labels: ", tokenized_dataset['train']['labels'])

Input ID Column([[499, 564, 19, 2974, 7, 3672, 77, 9864, 49, 6, 11, 27, 31, 51, 3, 9, 7523, 28, 192, 203, 13, 351, 5, 27, 1310, 1279, 30, 3, 9, 516, 213, 62, 1192, 3, 9, 126, 884, 8948, 21, 69, 349, 5, 37, 1288, 47, 12, 482, 3, 9, 72, 1139, 18, 4905, 11, 12954, 3459, 24, 133, 143, 34, 1842, 21, 722, 12, 1865, 70, 3744, 11, 592, 251, 5, 101, 708, 57, 7241, 1502, 45, 69, 722, 11, 13646, 1139, 585, 12, 734, 70, 523, 11, 1406, 979, 5, 101, 258, 876, 3, 9, 126, 1139, 3459, 24, 47, 321, 17307, 12817, 11, 514, 12, 169, 5, 101, 92, 6960, 3, 9, 381, 13, 126, 753, 6, 224, 38, 8, 1418, 21, 722, 12, 903, 70, 905, 892, 6, 1463, 70, 5022, 6, 11, 4237, 380, 3500, 367, 5, 37, 516, 47, 3, 9, 1269, 6, 11, 69, 722, 130, 182, 1095, 28, 8, 126, 8948, 5, 328, 435, 34, 12, 36, 231, 1842, 12, 169, 145, 8, 625, 80, 6, 11, 79, 9332, 8, 126, 753, 5, 101, 1509, 3, 9, 1516, 993, 16, 884, 5044, 11, 3813, 38, 3, 9, 741, 13, 8, 126, 8948, 5, 3, 11714, 8, 516, 6, 27, 47, 1966, 21, 2421, 8, 223, 18, 989, 1081, 21, 8, 8948, 5, 27, 92, 1279, 4799, 28, 8, 408, 372, 12, 766, 24, 8, 8948, 47, 17307, 12817, 11, 1139, 18, 4905, 5, 27, 31, 51, 2764, 13, 8, 161, 24, 27, 410, 30, 48, 516, 6, 11, 27, 31, 51, 4881, 24, 34, 56, 916, 12, 1656, 69, 722, 21, 203, 12, 369, 5, 156, 25, 133, 114, 12, 574, 140, 6, 82, 791, 1115, 19, 10447, 7, 3672, 77, 5, 12993, 49, 1741, 18958, 5, 287, 11, 82, 951, 381, 19, 11484, 3072, 314, 4165, 4327, 4327, 5, 27, 619, 44, 505, 2688, 1620, 1370, 1887, 5, 24906, 53, 19, 82, 14687, 5, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0], [499, 564, 19, 3695, 32, 25692, 11, 27, 31, 162, 118, 3, 9, 5812, 21, 505, 203, 5, 27, 43, 3, 9, 1101, 2987, 21, 1073, 11, 7131, 12, 482, 7007, 11, 6076, 1036, 2704, 21, 82, 481, 5, 555, 516, 24, 27, 31, 51, 1989, 2764, 13, 19, 8, 606, 13, 46, 367, 1036, 1585, 21, 82, 9185, 2854, 503, 5, 27, 1114, 12, 482, 3, 9, 1585, 24, 133, 995, 481, 12, 669, 44, 70, 293, 4974, 11, 370, 135, 28, 3, 9, 1196, 13, 1438, 12, 3391, 70, 1705, 13, 8, 1037, 5, 27, 1869, 633, 767, 464, 30, 8, 1585, 6, 84, 1285, 8296, 8, 5315, 6, 1577, 6076, 10561, 6, 11, 2421, 16396, 5, 27, 92, 3, 10975, 19131, 2479, 224, 38, 3075, 6, 11108, 7, 6, 11, 9301, 7, 12, 143, 8, 1036, 351, 72, 7007, 5, 37, 1585, 47, 3, 9, 1450, 1269, 28, 82, 481, 5, 328, 9332, 8, 6461, 11, 6440, 13, 271, 3, 179, 12, 669, 44, 70, 293, 4974, 6, 11, 79, 435, 8, 6076, 10561, 11, 19131, 2479, 12, 36, 182, 2690, 5, 37, 1585, 92, 2225, 140, 12, 1463, 1236, 2188, 11, 370, 3160, 72, 8877, 5, 555, 13, 8, 2428, 27, 7865, 383, 48, 516, 47, 3, 5833, 24, 8, 1585, 47, 3551, 12, 66, 481, 6, 6147, 13, 70, 2268, 1098, 42, 1904, 5, 27, 263, 417, 12, 169, 3, 9, 1139, 18, 4905, 408, 11, 370, 964, 3909, 30, 149, 12, 169, 8, 1585, 5, 27, 92, 5285, 8, 1585, 18710, 12, 766, 24, 34, 1279, 3085, 30, 315, 1904, 11, 3509, 7, 5, 9126, 6, 8, 606, 13, 8, 367, 1036, 1585, 47, 3, 9, 13948, 351, 5, 94, 2225, 140, 12, 169, 82, 6933, 11, 2268, 1098, 12, 482, 3, 9, 3487, 24, 141, 3, 9, 1465, 1113, 30, 82, 481, 31, 1036, 5, 27, 183, 373, 479, 21, 126, 1155, 12, 1172, 82, 2119, 11, 27, 31, 51, 2787, 12, 916, 2421, 3058, 1036, 2704, 21, 82, 481, 5, 3235, 2784, 10, 3695, 32, 25692, 314, 25794, 5550, 4576, 5894, 1768, 2555, 9526, 3, 26426, 6862, 4389, 3, 2729, 32, 17696, 172, 1741, 10718, 1963, 5, 287, 26100, 725, 10, 5747, 15, 21061, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0], [499, 564, 19, 2209, 1000, 32, 3068, 6, 11, 27, 31, 51, 46, 799, 2117, 8612, 28, 2391, 203, 13, 351, 5, 27, 31, 162, 373, 118, 24631, 57, 18979, 6, 11, 27, 333, 8, 1921, 13, 2627, 6112, 7, 1346, 11, 30, 97, 5, 555, 13, 8, 167, 10080, 1195, 27, 1279, 30, 47, 3, 9, 779, 5941, 12, 69, 3761, 31, 7, 16092, 358, 5, 37, 625, 358, 47, 21643, 11, 3, 15897, 12, 15568, 7, 6, 11, 34, 47, 2852, 5684, 1256, 12, 453, 95, 28, 8, 1710, 381, 13, 7534, 5, 27, 47, 7604, 12, 8, 372, 24, 47, 1966, 21, 1459, 11, 3, 10311, 8, 5941, 5, 101, 1279, 4799, 28, 8, 8702, 11, 11225, 12, 408, 3, 9, 126, 358, 24, 133, 36, 72, 3468, 6, 2918, 6, 11, 3919, 5, 37, 516, 808, 633, 767, 12, 743, 6, 11, 34, 47, 3, 9, 418, 13, 614, 161, 5, 299, 16, 8, 414, 6, 34, 47, 1494, 34, 5, 37, 126, 16092, 358, 65, 118, 3, 9, 779, 4179, 6, 11, 34, 65, 2139, 178, 12, 1172, 8, 1455, 11, 3949, 13, 69, 3761, 5, 27, 31, 51, 2764, 13, 8, 161, 24, 27, 410, 30, 48, 516, 6, 11, 27, 31, 51, 7335, 21, 8, 1004, 12, 43, 118, 3, 9, 294, 13, 34, 5, 94, 47, 3, 9, 4421, 351, 6, 68, 34, 92, 4436, 140, 3, 9, 418, 81, 372, 1981, 6, 682, 18, 6065, 53, 6, 11, 8, 3172, 13, 6597, 95, 18, 235, 18, 5522, 30, 8, 1251, 748, 5, 17857, 13, 161, 6, 27, 777, 2887, 97, 28, 82, 384, 11, 803, 5, 27, 92, 777, 13217, 2252, 11, 3, 17, 77, 2304, 53, 28, 12800, 5, 27, 31, 51, 373, 479, 21, 126, 1195, 12, 161, 30, 6, 11, 27, 31, 51, 373, 1036, 126, 378, 5, 156, 25, 31, 26, 114, 12, 129, 16, 1586, 28, 140, 6, 25, 54, 1535, 140, 57, 951, 44, 12811, 6348, 1630, 27904, 1458, 42, 57, 791, 44, 3, 1258, 1000, 32, 7, 202, 1741, 10718, 1963, 5, 1582, 5, 148, 54, 92, 253, 140, 44, 82, 234, 1115, 6, 84, 19, 489, 3420, 925, 6043, 1887, 18862, 5, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0], [499, 564, 19, 10135, 8331, 5667, 6, 11, 27, 31, 51, 3, 9, 1085, 15893, 28, 3, 9, 215, 13, 351, 5, 27, 1310, 2012, 3, 9, 516, 24, 1381, 2421, 11, 3, 10311, 3, 9, 126, 1085, 1998, 21, 82, 349, 5, 27, 708, 57, 3, 19175, 69, 750, 1085, 331, 12, 2862, 844, 213, 62, 228, 1172, 5, 27, 435, 24, 62, 130, 5489, 3, 9, 418, 13, 1055, 722, 250, 69, 1085, 433, 47, 396, 6446, 11, 97, 18, 10862, 5, 264, 6, 27, 3, 26474, 8, 433, 11, 263, 34, 1842, 21, 722, 12, 143, 9701, 5, 27, 92, 990, 3, 9, 126, 1070, 2066, 12, 3806, 72, 3433, 21, 69, 1085, 372, 5, 27, 261, 3, 9, 1196, 13, 1070, 6047, 6, 379, 569, 783, 6, 791, 6, 11, 1866, 3662, 5, 37, 2066, 47, 3, 9, 1269, 6, 11, 62, 1509, 3, 9, 1516, 993, 16, 8, 381, 13, 3433, 62, 130, 3, 11600, 5, 282, 3, 9, 741, 13, 175, 1112, 6, 69, 1085, 1936, 57, 7580, 16, 8, 166, 2893, 5, 27, 31, 51, 2764, 13, 8, 161, 24, 27, 410, 30, 48, 516, 6, 11, 27, 31, 51, 4881, 24, 34, 56, 916, 12, 199, 82, 349, 1604, 16, 8, 647, 5, 17857, 13, 161, 6, 27, 777, 1946, 9238, 5, 27, 253, 34, 12, 36, 3, 9, 8354, 11, 13948, 14687, 5, 27, 92, 777, 2887, 97, 28, 82, 384, 11, 803, 5, 156, 25, 43, 136, 746, 81, 82, 1085, 1998, 516, 42, 82, 27781, 6, 25, 54, 1535, 140, 44, 1768, 3840, 3, 18057, 4448, 968, 4729, 42, 1240, 226, 11849, 17, 152, 5667, 1741, 10718, 1963, 5, 1582, 5, 148, 54, 92, 719, 140, 44, 82, 234, 1115, 6, 84, 19, 507, 2394, 955, 4059, 26, 4197, 2409, 5, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0], [282, 2133, 20065, 27753, 6, 46, 905, 2743, 44, 3, 9, 8304, 889, 349, 6, 27, 15110, 3, 9, 775, 1921, 24, 831, 82, 3, 76, 17, 5463, 12365, 11, 2980, 12, 4602, 5, 37, 962, 3, 9, 8115, 116, 80, 13, 69, 12695, 820, 6, 3, 9, 1374, 23089, 11861, 6, 2196, 16, 8056, 343, 11573, 16, 70, 331, 9952, 1585, 5, 37, 5025, 60, 102, 28704, 130, 3, 13403, 70, 1357, 18, 5239, 2842, 11, 3, 5885, 14068, 441, 70, 2673, 5, 438, 3, 9, 1254, 13, 27844, 6, 27, 3, 30008, 26, 139, 8, 16, 3929, 9, 6267, 7, 13, 8, 682, 6, 4321, 3, 20424, 8, 331, 3369, 6, 16783, 6, 11, 3, 10067, 3620, 5, 27, 1869, 3, 11394, 716, 5569, 53, 147, 2356, 13, 1081, 6, 3, 19175, 4264, 6, 11, 13646, 9517, 2505, 12, 28598, 8, 5465, 1137, 13, 8, 5025, 60, 102, 28704, 5, 499, 73, 12301, 1007, 3148, 12, 8978, 11, 23569, 1388, 12, 2736, 3725, 2237, 140, 12, 2862, 3, 9, 9240, 8143, 16, 8, 358, 31, 7, 4648, 5, 304, 27748, 63, 8, 1419, 6, 27, 11194, 26, 4799, 28, 69, 372, 13, 8702, 6, 1260, 964, 11, 22874, 3909, 12, 1115, 8, 8143, 11, 4028, 3, 9, 3452, 1127, 5, 421, 6018, 2231, 741, 15, 26, 16, 8, 1574, 3161, 13, 8, 962, 6, 3, 22938, 7452, 11, 10581, 12, 8, 1188, 31, 7, 331, 9952, 1585, 5, 37, 1188, 7103, 70, 14968, 17142, 21, 69, 9005, 11, 1231, 1773, 6, 3, 60, 27236, 51, 53, 70, 2019, 16, 69, 364, 5, 94, 19, 4413, 114, 175, 24, 5607, 140, 13, 8, 14968, 5044, 24, 639, 45, 11795, 1561, 982, 11, 492, 3, 9, 1465, 1113, 30, 69, 820, 31, 1623, 5, 27, 240, 14968, 6064, 16, 82, 1418, 12, 2862, 11, 7785, 2428, 28, 16, 729, 76, 485, 11, 11723, 5, 499, 73, 12301, 1007, 3148, 12, 8978, 11, 2987, 21, 3, 6930, 5916, 772, 1262, 140, 12, 8182, 8193, 4454, 5, 2133, 20065, 27753, 6288, 3440, 1179, 4198, 21423, 3, 4450, 7, 17, 28797, 1337, 20065, 834, 1538, 7, 8371, 5605, 1741, 51, 7, 29, 5, 1677, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]])
Labels:  Column([[3, 2, 121, 4350, 121, 10, 96, 18620, 7, 3672, 77, 9864, 49, 1686, 96, 15, 1963, 121, 10, 96, 4470, 7, 3672, 77, 5, 12993, 49, 1741, 18958, 5, 287, 1686, 96, 6399, 121, 10, 96, 6348, 3072, 314, 4165, 4327, 4327, 1686, 96, 16899, 121, 10, 96, 29916, 49, 1686, 96, 9, 26, 12039, 121, 10, 96, 927, 2688, 1620, 1370, 1887, 1686, 96, 10041, 4350, 121, 10, 1823, 567, 6, 96, 16137, 121, 10, 1823, 567, 6, 96, 107, 32, 115, 969, 121, 10, 96, 5991, 173, 1222, 121, 2, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0], [3, 2, 121, 4350, 121, 10, 96, 439, 76, 32, 25692, 1686, 96, 15, 1963, 121, 10, 96, 2729, 32, 17696, 172, 1741, 10718, 1963, 5, 287, 1686, 96, 6399, 121, 10, 96, 1220, 2555, 9526, 3, 26426, 6862, 4389, 1686, 96, 16899, 121, 10, 96, 1409, 89, 24901, 1686, 96, 9, 26, 12039, 121, 10, 96, 4853, 4060, 5550, 4576, 5894, 1686, 96, 10041, 4350, 121, 10, 1823, 567, 6, 96, 16137, 121, 10, 1823, 567, 6, 96, 107, 32, 115, 969, 121, 10, 96, 439, 155, 15, 21061, 121, 2, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0], [3, 2, 121, 4350, 121, 10, 96, 439, 9, 1000, 32, 3068, 1686, 96, 15, 1963, 121, 10, 96, 1258, 1000, 32, 7, 202, 1741, 10718, 1963, 5, 1582, 1686, 96, 6399, 121, 10, 96, 632, 23702, 1630, 27904, 1458, 1686, 96, 16899, 121, 10, 96, 2256, 2117, 8612, 1686, 96, 9, 26, 12039, 121, 10, 96, 940, 3420, 925, 6043, 1887, 18862, 1686, 96, 10041, 4350, 121, 10, 1823, 567, 6, 96, 16137, 121, 10, 1823, 567, 6, 96, 107, 32, 115, 969, 121, 10, 96, 8123, 6408, 2252, 121, 2, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0], [3, 2, 121, 4350, 121, 10, 96, 27280, 11849, 8331, 5667, 1686, 96, 15, 1963, 121, 10, 96, 138, 994, 11849, 17, 152, 5667, 1741, 10718, 1963, 5, 1582, 1686, 96, 6399, 121, 10, 96, 1220, 3840, 3, 18057, 4448, 968, 4729, 1686, 96, 16899, 121, 10, 96, 7, 4529, 15893, 1686, 96, 9, 26, 12039, 121, 10, 96, 2606, 2394, 955, 4059, 26, 4197, 2409, 1686, 96, 10041, 4350, 121, 10, 1823, 567, 6, 96, 16137, 121, 10, 1823, 567, 6, 96, 107, 32, 115, 969, 121, 10, 96, 23351, 138, 9238, 121, 2, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0], [3, 2, 121, 4350, 121, 10, 96, 329, 23, 20065, 27753, 1686, 96, 15, 1963, 121, 10, 96, 2720, 157, 32, 834, 1538, 7, 8371, 5605, 1741, 51, 7, 29, 5, 1677, 1686, 96, 6399, 121, 10, 96, 1220, 2555, 3, 4241, 3, 26144, 10635, 4056, 1686, 96, 16899, 121, 10, 96, 9, 75, 13362, 2743, 1686, 96, 9, 26, 12039, 121, 10, 96, 2368, 4198, 21423, 3, 4450, 7, 17, 28797, 1686, 96, 10041, 4350, 121, 10, 1823, 567, 6, 96, 16137, 121, 10, 1823, 567, 6, 96, 107, 32, 115, 969, 121, 10, 96, 23351, 138, 3, 29782, 121, 2, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]])

In [7]:
from transformers import T5ForConditionalGeneration

# model = T5ForConditionalGeneration.from_pretrained("t5-large")
model = T5ForConditionalGeneration.from_pretrained('./model/t5_model')
# tokenizer = T5ForConditionalGeneration.from_pretrained('./model/t5_model')


# tokenizer.save_pretrained('./model/t5_tokenizer')
# model.save_pretrained('./model/t5_model')

In [62]:
tokenized_dataset['train'][0]

{'input_text': "My name is Konstantin Becker, and I'm a developer with two years of experience. I recently worked on a project where we built a new customer portal for our company. The goal was to create a more user-friendly and intuitive interface that would make it easier for customers to manage their accounts and access information. We started by gathering requirements from our customers and conducting user research to understand their needs and pain points. We then designed a new user interface that was both visually appealing and easy to use. We also implemented a number of new features, such as the ability for customers to view their account history, track their orders, and submit support tickets online. The project was a success, and our customers were very happy with the new portal. They found it to be much easier to use than the old one, and they appreciated the new features. We saw a significant increase in customer satisfaction and engagement as a result of the new portal. Throughout the project, I was responsible for developing the back-end code for the portal. I also worked closely with the design team to ensure that the portal was visually appealing and user-friendly. I'm proud of the work that I did on this project, and I'm confident that it will continue to benefit our customers for years to come. If you would like to contact me, my email address is konstantin.becker@gmail.com and my phone number is 0475 4429797. I live at 826 Webster Street. Quilting is my hobby.",
 'target_json': '{"name": "Konstantin Becker", "email": "konstantin.becker@gmail.com", "phone": "0475 4429797", "job": "developer", "address": "826 Webster Street", "username": NaN, "url": NaN, "hobby": "Quilting"}',
 'input_ids': [499,
  564,
  19,
  2974,
  7,
  3672,
  77,
  9864,
  49,
  6,
  11,
  27,
  31,
  51,
  3,
  9,
  7523,
  28,
  192,
  203,
  13,
  351,
  5,
  27,
  1310,
  1279,
  30,
  3,
  9,
  516,
  213,
  62,
  1192,
  3,
  9,
  126,
  884,
  8948,
  21,
  69,
  349,
  5,
  37,
  1288,
  47,
  12,
  482,
  3,
  9,
  72,
  1139,
  18,
  4905,
  11,
  12954,
  3459,
  24,
  133,
  143,
  34,
  1842,
  21,
  722,
  12,
  1865,
  70,
  3744,
  11,
  592,
  251,
  5,
  101,
  708,
  57,
  7241,
  1502,
  45,
  69,
  722,
  11,
  13646,
  1139,
  585,
  12,
  734,
  70,
  523,
  11,
  1406,
  979,
  5,
  101,
  258,
  876,
  3,
  9,
  126,
  1139,
  3459,
  24,
  47,
  321,
  17307,
  12817,
  11,
  514,
  12,
  169,
  5,
  101,
  92,
  6960,
  3,
  9,
  381,
  13,
  126,
  753,
  6,
  224,
  38,
  8,
  1418,
  21,
  722,
  12,
  903,
  70,
  905,
  892,
  6,
  1463,
  70,
  5022,
  6,
  11,
  4237,
  380,
  3500,
  367,
  5,
  37,
  516,
  47,
  3,
  9,
  1269,
  6,
  11,
  69,
  722,
  130,
  182,
  1095,
  28,
  8,
  126,
  8948,
  5,
  328,
  435,
  34,
  12,
  36,
  231,
  1842,
  12,
  169,
  145,
  8,
  625,
  80,
  6,
  11,
  79,
  9332,
  8,
  126,
  753,
  5,
  101,
  1509,
  3,
  9,
  1516,
  993,
  16,
  884,
  5044,
  11,
  3813,
  38,
  3,
  9,
  741,
  13,
  8,
  126,
  8948,
  5,
  3,
  11714,
  8,
  516,
  6,
  27,
  47,
  1966,
  21,
  2421,
  8,
  223,
  18,
  989,
  1081,
  21,
  8,
  8948,
  5,
  27,
  92,
  1279,
  4799,
  28,
  8,
  408,
  372,
  12,
  766,
  24,
  8,
  8948,
  47,
  17307,
  12817,
  11,
  1139,
  18,
  4905,
  5,
  27,
  31,
  51,
  2764,
  13,
  8,
  161,
  24,
  27,
  410,
  30,
  48,
  516,
  6,
  11,
  27,
  31,
  51,
  4881,
  24,
  34,
  56,
  916,
  12,
  1656,
  69,
  722,
  21,
  203,
  12,
  369,
  5,
  156,
  25,
  133,
  114,
  12,
  574,
  140,
  6,
  82,
  791,
  1115,
  19,
  10447,
  7,
  3672,
  77,
  5,
  12993,
  49,
  1741,
  18958,
  5,
  287,
  11,
  82,
  951,
  381,
  19,
  11484,
  3072,
  314,
  4165,
  4327,
  4327,
  5,
  27,
  619,
  44,
  505,
  2688,
  1620,
  1370,
  1887,
  5,
  24906,
  53,
  19,
  82,
  14687,
  5,
  1,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0],
 'attention_mask': [1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0],
 'labels': [3,
  2,
  121,
  4350,
  121,
  10,
  96,
  18620,
  7,
  3672,
  77,
  9864,
  49,
  1686,
  96,
  15,
  1963,
  121,
  10,
  96,
  4470,
  7,
  3672,
  77,
  5,
  12993,
  49,
  1741,
  18958,
  5,
  287,
  1686,
  96,
  6399,
  121,
  10,
  96,
  6348,
  3072,
  314,
  4165,
  4327,
  4327,
  1686,
  96,
  16899,
  121,
  10,
  96,
  29916,
  49,
  1686,
  96,
  9,
  26,
  12039,
  121,
  10,
  96,
  927,
  2688,
  1620,
  1370,
  1887,
  1686,
  96,
  10041,
  4350,
  121,
  10,
  1823,
  567,
  6,
  96,
  16137,
  121,
  10,
  1823,
  567,
  6,
  96,
  107,
  32,
  115,
  969,
  121,
  10,
  96,
  5991,
  173,
  1222,
  121,
  2,
  1,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0]}

In [8]:
from transformers import TrainingArguments, Trainer

training_args = TrainingArguments(
    output_dir="./t5-json-model",
    eval_strategy="epoch",
    learning_rate=3e-5,
    per_device_train_batch_size=4,
    per_device_eval_batch_size=4,
    num_train_epochs=3,
    weight_decay=0.01,
    save_total_limit=2,
    do_predict=True,
    fp16=True,  # if you're using a GPU with mixed precision support
)

trainer = Trainer(
    model=model,
    args=training_args,
    train_dataset=tokenized_dataset["train"],
    eval_dataset=tokenized_dataset["test"],
    tokenizer=tokenizer,
)

trainer.train()

/tmp/ipykernel_1913/3544683791.py:16: FutureWarning: `tokenizer` is deprecated and will be removed in version 5.0.0 for `Trainer.__init__`. Use `processing_class` instead.
  trainer = Trainer(

OutOfMemoryError: CUDA out of memory. Tried to allocate 20.00 MiB. GPU 0 has a total capacity of 4.00 GiB of which 0 bytes is free. Including non-PyTorch memory, this process has 17179869184.00 GiB memory in use. Of the allocated memory 10.95 GiB is allocated by PyTorch, and 12.31 MiB is reserved by PyTorch but unallocated. If reserved but unallocated memory is large try setting PYTORCH_CUDA_ALLOC_CONF=expandable_segments:True to avoid fragmentation.  See documentation for Memory Management  (https://pytorch.org/docs/stable/notes/cuda.html#environment-variables)

In [2]:
import transformers
transformers.__version__

'4.57.1'